main: com.chup.mobcoinsplus.Main
version: ${project.version}
api-version: 1.13
name: ${project.name}
authors:
  - GupAChup
  - MyApaulogies
description: A helpful plugin that allows mobs to drop currency!
commands:
  mobcoins:
    aliases: mc
    description: MobCoins commands.
  mobshop:
    aliases: ms
    description: Opens MobCoins shop.
permissions:
  mobcoinsplus.admin:
    default: op
    mobcoinsplus.mobshop: true
    mobcoinsplus.amount: true
    mobcoinsplus.top: true
    mobcoinsplus.*: true
